name             "subway"
maintainer       "Joshua Mervine"
maintainer_email "joshua@mervine.net"
license          "MIT"
description      "Installs/Configures subway"
long_description IO.read(File.join(File.dirname(__FILE__), 'README.md'))
version          "0.1.0"
depends          "git"
depends          "nginx"
depends          "nodejs"
depends          "npm"
depends          "nginx_proxy"
